const statesArray = {
  Alabama: '.5',
  Alaska: '.8',
  Arizona: '.5',
  Arkansas: '.1',
  California: '.8',
  Colorado: '.1',
  Connecticut: '.1',
  Delaware: '.5',
  Florida: '.8',
  Georgia: '.1',
  Hawaii: '.5',
  Idaho: '.1',
  Illinois: '.1',
  Indiana: '.8',
  Iowa: '1',
  Kansas: '.5',
  Kentucky: '1',
  Louisiana: '.4',
  Maine: '.1',
  Maryland: '1',
  Massachusetts: '.8',
  Michigan: '.1',
  Minnesota: '.5',
  Mississippi: '.1',
  Missouri: '1',
  Montana: '.1',
  Nebraska: '1',
  Nevada: '.5',
  'New Hampshire': '.8',
  'New Jersey': '1',
  'New Mexico': '.6',
  'New York': '1',
  'North Carolina': '1',
  'North Dakota': '.8',
  Ohio: '.1',
  Oklahoma: '.2',
  Oregon: '1',
  Pennsylvania: '.5',
  'Rhode Island': '1',
  'South Carolina': '1',
  'South Dakota': '.5',
  Tennessee: '.1',
  Texas: '.8',
  Utah: '.8',
  Vermont: '.5',
  Virginia: '.1',
  Washington: '.1',
  'West Virginia': '.5',
  Wisconsin: '.4',
  Wyoming: '.4',
};

module.exports = statesArray;
